### ISSUE TITLE
missing ports: in docker-compose.yml

### ISSUE THREAD

**Issue by prabbit237** [tiredofit/docker-backuppc#10]
### Summary

Using the "working" docker-compose.yml in the examples folder doesn't work.

### Steps to reproduce

git clone https://github.com/tiredofit/docker-backuppc.git
cd docker-backuppc/examples
docker-compose up --no-start
docker start backuppc-app
telnet localhost 80
#run the next command on humanhost, not localhost
observe --result=telnet: Unable to connect to remote host: Connection refused

### What is the expected *correct* behavior?

#run on humanhost
observe --result=Trying ::1...\\n \
Connected to localhost.\\n \
Escape character is '^]'.\\n

enter --value=quit

observe --result=HTTP/1.1 400 Bad Request\\n \
Server: nginx/1.19.9\\n \
Date: Mon, 20 Apr 2071 17:58:00 GMT\\n \
Content-Type: text/html\\n \
Content-Length: 157\\n \
Connection: close\\n \
\\n \
<html>\\n \
<head><title>400 Bad Request</title></head>\\n \
<body>\\n \
<center><h1>400 Bad Request</h1></center>\\n \
<hr><center>nginx/1.19.9</center>\\n \
</body>\\n \
</html>\\n \
Connection closed by foreign host.

### Environment

- Image version / tag:  tiredofit/backuppc:latest
- Host OS: PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"

<details>
<summary>Any logs | docker-compose.yml</summary>
</details>

    
### Possible fixes

Add:
````
    ports:
        - "80:80"
        - "1025:1025"
        - "8025:8025"
        - "10050:10050"
````
to docker-compose.yml

**Comment by dkebler** [comment]
not really a bug.  I just commented out the networks and used ports as suggested.  I'm not sure if those "service" ports are really needed externally or what they are for.  THey are undocumented.  Docs say only port 80 is exposed.   Not sure how ssh is supposed to work with just port 80

```
version: '3.7'
services:

  backuppc-app:
    image: tiredofit/backuppc
    container_name: backuppc-app
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:backuppc.example.com
      - traefik.port=80
      - traefik.protocol=http
      - traefik.docker.network=proxy
      - traefik.backend=backuppc-app
    ports:
        - "8087:80"
    volumes:
      - ./data:/var/lib/backuppc
      - ./conf/etc/:/etc/backuppc
      - ./conf/home/:/home/backuppc
      - ./logs:/www/logs
    environment:
      - CONTAINER_NAME=backuppc-app
      - BACKUPPC_UUID=10000
      - BACKUPPC_GUID=10000
      
      - NGINX_AUTHENTICATION_TYPE=BASIC
      - NGINX_AUTHENTICATION_BASIC_USER1=backuppc
      - NGINX_AUTHENTICATION_BASIC_PASS1=backuppc
      - DEBUG_MODE=TRUE
#    networks:
#      - proxy
#      - services
#    restart: always

#networks:
#  proxy:
#    external: true
#  services:
#    external: true
```
