### ISSUE TITLE
Error in log: can't open 'BackupPC-4.3.1.tar.gz': No such file or directory

### ISSUE THREAD

**Issue by morevnaproject** [tiredofit/docker-backuppc#2]
I am trying to start this container and got following in logs:
```
backuppc                 | [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
backuppc                 | [INFO] ** [nginx] Starting nginx 1.17.9
backuppc                 | [INFO] ** [fcgiwrap] Starting fcgiwrap
backuppc                 | [INFO] ** [zabbix] Starting Zabbix Agent
backuppc                 | [s6-init] ensuring user provided files have correct perms...nginx: [emerg] open() "/www/logs/nginx/error.log" failed (2: No such file or directory)
backuppc                 | exited 0.
backuppc                 | [fix-attrs.d] applying ownership & permissions fixes...
backuppc                 | [fix-attrs.d] 00-functions: applying... 
backuppc                 | [fix-attrs.d] 00-functions: exited 0.
backuppc                 | [fix-attrs.d] 01-s6: applying... 
backuppc                 | [fix-attrs.d] 01-s6: exited 0.
backuppc                 | [fix-attrs.d] 02-zabbix: applying... 
backuppc                 | [fix-attrs.d] 02-zabbix: exited 0.
backuppc                 | [fix-attrs.d] 03-logrotate: applying... 
backuppc                 | [fix-attrs.d] 03-logrotate: exited 0.
backuppc                 | [fix-attrs.d] done.
backuppc                 | [cont-init.d] executing container initialization scripts...
backuppc                 | [cont-init.d] 00-startup: executing... 
backuppc                 | [NOTICE] ** [container-init] Detected Container that has been restarted - Cleaning '/tmp/state' files
backuppc                 | [cont-init.d] 00-startup: exited 0.
backuppc                 | [cont-init.d] 01-timezone: executing... 
backuppc                 | [NOTICE] ** [timezone] Setting timezone to 'America/Vancouver'
backuppc                 | cp: can't create '/etc/localtime': File exists
backuppc                 | [cont-init.d] 01-timezone: exited 0.
backuppc                 | [cont-init.d] 02-permissions: executing... 
backuppc                 | [cont-init.d] 02-permissions: exited 0.
backuppc                 | [cont-init.d] 03-zabbix: executing... 
backuppc                 | [cont-init.d] 03-zabbix: exited 0.
backuppc                 | [cont-init.d] 04-cron: executing... 
backuppc                 | [cont-init.d] 04-cron: exited 0.
backuppc                 | [cont-init.d] 05-smtp: executing... 
backuppc                 | [NOTICE] ** [smtp] Sendmail replaced and enabled to route mail to: 'postfix-relay'
backuppc                 | [cont-init.d] 05-smtp: exited 0.
backuppc                 | [cont-init.d] 10-nginx: executing... 
backuppc                 | /etc/nginx/nginx.conf ATTRIB 
backuppc                 | [NOTICE] ** [nginx] Disable Nginx FastCGI HTTPS Termination Support
backuppc                 | [cont-init.d] 10-nginx: exited 0.
backuppc                 | [cont-init.d] 11-nginx-config-reload: executing... 
backuppc                 | [cont-init.d] 11-nginx-config-reload: exited 0.
backuppc                 | [cont-init.d] 20-backuppc: executing... 
backuppc                 | [WARN] ** [backuppc] First run of the container. BackupPC will be installed.
backuppc                 | [WARN] ** [backuppc] If exist, configuration and data will be reused and upgraded as needed.
backuppc                 | addgroup: group 'backuppc' in use
backuppc                 | adduser: user 'backuppc' in use
backuppc                 | tar: can't open 'BackupPC-4.3.1.tar.gz': No such file or directory
backuppc                 | /var/run/s6/etc/cont-init.d/20-backuppc: line 29: cd: /usr/src/BackupPC-4.3.1: No such file or directory
backuppc                 | [INFO] ** [backuppc] Container initialization complete
backuppc                 | [cont-init.d] 20-backuppc: exited 0.
backuppc                 | [cont-init.d] 99-container: executing... 
backuppc                 | [cont-init.d] 99-container: exited 0.
backuppc                 | [cont-init.d] done.
backuppc                 | [services.d] starting services
backuppc                 | [services.d] done.
backuppc                 | [INFO] ** [zabbix] Starting Zabbix Agent
backuppc                 | [INFO] ** [fcgiwrap] Starting fcgiwrap
backuppc                 | [INFO] ** [nginx] Starting nginx 1.17.9
backuppc                 | [INFO] ** [cron] Starting cron
```

Note this line:
```
backuppc                 | tar: can't open 'BackupPC-4.3.1.tar.gz': No such file or directory
backuppc                 | /var/run/s6/etc/cont-init.d/20-backuppc: line 29: cd: /usr/src/BackupPC-4.3.1: No such file or directory
```

Here is what I see in the web interface:
![screenshot_001](https://user-images.githubusercontent.com/332868/78212986-866a6180-74db-11ea-8b13-06187a2caf3e.png)

Opened shell inside container and checked `/usr/src/` dir - it is empty.

Have following content in `docker-compose.yml` for backuppc:

```
  backuppc:
    image: tiredofit/backuppc
    container_name: backuppc
    volumes:
      - /home/backup:/var/lib/backuppc
      - ./c-backuppc-data/etc:/etc/backuppc
      - ./c-backuppc-data/home:/home/backuppc
      - /home/backup/logs:/www/logs
      - /etc/localtime:/etc/localtime:ro
    environment:
      - VIRTUAL_HOST=<<HIDDEN>>
      - VIRTUAL_PORT=80
      - ZABBIX_HOSTNAME=backuppc
      - BACKUPPC_ADMIN_USER=<<HIDDEN>>
      - BACKUPPC_ADMIN_PASS=<<HIDDEN>>
      - BACKUPPC_UUID=1111
      - BACKUPPC_GUID=1111
      - AUTHENTICATION_TYPE=BASIC
      - LETSENCRYPT_HOST=<<HIDDEN>>
      - LETSENCRYPT_EMAIL=<<HIDDEN>>
```
